stages:
  - build
  - test
  - deploy
  - sync

sync_github:
  stage: sync
  image: docker:1.12.1-git
  script:
   - git fetch --prune
   - git push --prune git@github.com:hartcode/react-meetup-native.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/* 
