language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - sys-img-armeabi-v7a-android-23
    - sys-img-x86-addon-google_apis-google-23
    - extra-android-m2repository
before-install: cd etsy-android
script: gradle build connectedCheck
