language: android
dist: precise
sudo: required
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
notifications:
    slack: hartcode:GqPCaLxnPqXfPJBMjJbEvG81
before_install:
    - cd native/android
    - sudo apt-get -qq update
    - sudo apt-get install -y build-essential libssl-dev
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
    - source ~/.profile
    - nvm ls-remote
    - nvm install 7.10
    - nvm use 7.10
    - node -v
    - npm install -g react-native-cli
    - npm install
script: ./gradlew build
addons:
  code_climate:
    repo_token: 88e230696fc91873bf0c15bee7de1fcdad7d63b351ffdeae823f68f14ef20f2a
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
